#! /bin/bash

# generate year/month folders, if needed
MONTH_DIR="$(date +%Y)/$(date +%m%B)"
mkdir -p $MONTH_DIR


# Check for today's page and generate if needed
TODAY=$(date +%b_%d_%a)
PAGE_FILE="$MONTH_DIR/$TODAY.ipynb"
if [ ! -f $PAGE_FILE ]
then
touch $PAGE_FILE
cat > $PAGE_FILE <<- EOM
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# $TODAY"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {},
   "outputs": [],
   "source": [
    "%pylab inline\n",
    "import matplotlib\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1
}
EOM
fi


# open today's page
jupyter notebook $PAGE_FILE
